# Generated by Django 5.2.6 on 2025-09-17 20:21

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinoplastika', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetailSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='blog_item_details/og/')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='blog_item_details/twitter/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='blog_item_details/logo/')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='rinoplastika.servicedetail')),
            ],
            options={
                'verbose_name': 'Service Detail SEO',
                'verbose_name_plural': 'Service Detail SEOs',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceDetailSeoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.CharField(blank=True, max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rinoplastika.servicedetailseo')),
            ],
            options={
                'verbose_name': 'Service Detail SEO Translation',
                'db_table': 'rinoplastika_servicedetailseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
