# Generated by Django 5.2.6 on 2025-10-14 09:43

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon Nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-poçt')),
                ('address', models.CharField(blank=True, default='Atatür prospekti 1010', max_length=250, verbose_name='Ünvan')),
                ('map_embed', models.TextField(blank=True, help_text='Bütün iframe kodunu və ya embed linkini buraya yapışdırın', verbose_name='Google Maps Embed URL / iframe')),
            ],
            options={
                'verbose_name': 'Əlaqə Məlumatı',
                'verbose_name_plural': 'Əlaqə Məlumatları',
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_url', models.URLField(blank=True, default='http://stormpromo.az/', verbose_name='Yaradıcı Link')),
            ],
            options={
                'verbose_name': 'Footer Məlumatı',
                'verbose_name_plural': 'Footer Məlumatları',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Ana Səhifə'), ('about', 'Haqqımızda'), ('services', 'Xidmətlər (Siyahı Səhifəsi)'), ('blog', 'Blog (Siyahı Səhifəsi)'), ('contact', 'Əlaqə')], max_length=50, unique=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og-images/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seo/logos/')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Səhifə SEO',
                'verbose_name_plural': 'Səhifələr üçün SEO',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Preloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='preloader/', verbose_name='Preloader Şəkli')),
            ],
            options={
                'verbose_name': 'Preloader',
                'verbose_name_plural': 'Preloader',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Logo Şəkli')),
            ],
            options={
                'verbose_name': 'Sayt Logo',
                'verbose_name_plural': 'Sayt Logoları',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('telegram', 'Telegram')], max_length=50, verbose_name='Sosial şəbəkə')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Sosial Media Linki',
                'verbose_name_plural': 'Sosial Media Linkləri',
            },
        ),
        migrations.CreateModel(
            name='FooterInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description_text', models.TextField(blank=True, default='Qulaq-burun-boğaz və baş-boyun cərrahiyyəsi uzmanı, Avropa sertifikatlı üz plastik cərrah və otorinolarinqoloq', verbose_name='Footer Təsviri')),
                ('copyright_text', models.CharField(blank=True, default='© 2025 Dr. Kamil Cəfərov', max_length=200, verbose_name='Footer Mətni')),
                ('creation_text', models.CharField(blank=True, default='STORM', max_length=100, verbose_name='Yaradıcı Mətn')),
                ('slide_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Slider Mətni')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.footerinfo')),
            ],
            options={
                'verbose_name': 'Footer Məlumatı Translation',
                'db_table': 'core_footerinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageSEOTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.pageseo')),
            ],
            options={
                'verbose_name': 'Səhifə SEO Translation',
                'db_table': 'core_pageseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PreloaderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('display_text', models.CharField(blank=True, default='Dr. Kamil Cəfərov | Yüklənir', max_length=200, verbose_name='Yüklənir Mətn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.preloader')),
            ],
            options={
                'verbose_name': 'Preloader Translation',
                'db_table': 'core_preloader_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SidebarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('sidebar_text', models.CharField(blank=True, default='', verbose_name='Sidebar Mətn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sidebar')),
            ],
            options={
                'verbose_name': 'Sidebar Translation',
                'db_table': 'core_sidebar_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteLogoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='Alt mətn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sitelogo')),
            ],
            options={
                'verbose_name': 'Sayt Logo Translation',
                'db_table': 'core_sitelogo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
