# Generated by Django 5.2.6 on 2025-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name': 'Sayt Logo', 'verbose_name_plural': 'Logo'},
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='creation_url',
            field=models.URLField(blank=True, default='https://vrproduction.az/', verbose_name='Yaradıcı Link'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='page_type',
            field=models.CharField(choices=[('home', 'Ana Səhifə'), ('about', 'Haqqımızda'), ('services', 'Xidmətlər (Siyahı Səhifəsi)'), ('blog', 'Blog (Siyahı Səhifəsi)'), ('contact', 'Əlaqə'), ('appointment', 'Onlayn Konsultasiya')], max_length=50, unique=True),
        ),
    ]
