# Generated by Django 5.2.6 on 2025-10-16 09:12

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Blog Bölməsi',
                'verbose_name_plural': 'Bloglar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Comment Bölməsi',
                'verbose_name_plural': 'Rəylər',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FAQ Bölməsi',
                'verbose_name_plural': 'FAQ-lar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Contentləri',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Bölməsi',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rəqəm 1')),
                ('num2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rəqəm 2')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/intro_section/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Intro Section',
                'verbose_name_plural': 'Haqqımda',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube linki')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Servislər',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(verbose_name='Yayın tarixi')),
                ('writer', models.CharField(max_length=255, verbose_name='Yazıçı adı')),
                ('writer_photo', models.ImageField(blank=True, null=True, upload_to='blog/writers/', verbose_name='Yazıçı şəkli')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.blog', verbose_name='Əlaqəli Blog')),
            ],
            options={
                'verbose_name': 'Blog Maddəsi',
                'verbose_name_plural': 'Blog Maddələri',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField(default=5, verbose_name='Ulduz sayı (1-5)')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Xəstə adı')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vəzifə / Pozisiya')),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='comments/patients/', verbose_name='Xəstə şəkli')),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='comments/before_after/', verbose_name='Əvvəl şəkli')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='comments/before_after/', verbose_name='Sonra şəkli')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.comment', verbose_name='Əlaqəli Rəy')),
            ],
            options={
                'verbose_name': 'Rəy Maddəsi',
                'verbose_name_plural': 'Rəy Maddələri',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.faqs', verbose_name='Əlaqəli FAQ')),
            ],
            options={
                'verbose_name': 'FAQ Maddəsi',
                'verbose_name_plural': 'FAQ Maddələri',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSectionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/hero_section_images/')),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.herosection')),
            ],
            options={
                'verbose_name': 'Hero Section Image',
                'verbose_name_plural': 'Hero Section Şəkilləri',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='İkon sinfi (məs: fa-solid fa-star)')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.services', verbose_name='Əlaqəli Servis')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Servis Elementləri',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.blogitem')),
            ],
            options={
                'verbose_name': 'Blog Maddəsi Translation',
                'db_table': 'home_blogitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_word', models.CharField(max_length=100, verbose_name='Əsas söz')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Təsvir')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.blog')),
            ],
            options={
                'verbose_name': 'Blog Bölməsi Translation',
                'db_table': 'home_blog_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommentItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('text', models.TextField(verbose_name='Rəy')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.commentitem')),
            ],
            options={
                'verbose_name': 'Rəy Maddəsi Translation',
                'db_table': 'home_commentitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_word', models.CharField(max_length=100, verbose_name='Əsas söz')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.comment')),
            ],
            options={
                'verbose_name': 'Comment Bölməsi Translation',
                'db_table': 'home_comment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqsItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=255, verbose_name='Sual')),
                ('answer', models.TextField(verbose_name='Cavab')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.faqsitem')),
            ],
            options={
                'verbose_name': 'FAQ Maddəsi Translation',
                'db_table': 'home_faqsitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_word', models.CharField(max_length=100, verbose_name='Əsas söz')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Təsvir')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.faqs')),
            ],
            options={
                'verbose_name': 'FAQ Bölməsi Translation',
                'db_table': 'home_faqs_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.herocontent')),
            ],
            options={
                'verbose_name': 'Hero Content Translation',
                'db_table': 'home_herocontent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.herosection')),
            ],
            options={
                'verbose_name': 'Hero Section Translation',
                'db_table': 'home_herosection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IntroSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_word', models.CharField(max_length=100, verbose_name='Əsas söz')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq')),
                ('text1', models.TextField(blank=True, null=True, verbose_name='Mətn 1')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='Mətn 2')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.introsection')),
            ],
            options={
                'verbose_name': 'Intro Section Translation',
                'db_table': 'home_introsection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.serviceitem')),
            ],
            options={
                'verbose_name': 'Service Item Translation',
                'db_table': 'home_serviceitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServicesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('rotate_word', models.CharField(max_length=100, verbose_name='Dönən söz')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.services')),
            ],
            options={
                'verbose_name': 'Services Translation',
                'db_table': 'home_services_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
