# Generated by Django 5.2.6 on 2025-10-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introsection',
            name='num1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Rəqəm 1 (məs: 23+)'),
        ),
        migrations.AlterField(
            model_name='introsection',
            name='num2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Rəqəm 2 (məs: 23k+)'),
        ),
    ]
