# Generated by Django 5.2.6 on 2025-10-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_introsection_num1_alter_introsection_num2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitemtranslation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='serviceitemtranslation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
