# Generated by Django 5.2.6 on 2025-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogitemtranslation_slug_serviceitemtranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='home/faqs/', verbose_name='Şəkil'),
        ),
    ]
