# Generated by Django 5.2.6 on 2025-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faqs_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentitem',
            name='after_photo',
        ),
        migrations.RemoveField(
            model_name='commentitem',
            name='before_photo',
        ),
        migrations.AddField(
            model_name='comment',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='comments/before_after/', verbose_name='Sonra şəkli'),
        ),
        migrations.AddField(
            model_name='comment',
            name='before_photo',
            field=models.ImageField(blank=True, null=True, upload_to='comments/before_after/', verbose_name='Əvvəl şəkli'),
        ),
    ]
