# Generated by Django 5.2.6 on 2025-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_commentitem_after_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/items/', verbose_name='Şəkil'),
        ),
    ]
