# Generated by Django 5.2.6 on 2025-10-16 16:51

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='appointment/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Onlayn Konsultasiya',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='blogitem',
            options={'verbose_name': 'Blog Maddəsi', 'verbose_name_plural': 'Blog Detalları'},
        ),
        migrations.AlterModelOptions(
            name='commentitem',
            options={'verbose_name': 'Rəy Maddəsi', 'verbose_name_plural': 'Rəy Detalları'},
        ),
        migrations.AlterModelOptions(
            name='faqsitem',
            options={'verbose_name': 'FAQ Maddəsi', 'verbose_name_plural': 'FAQ Detalları'},
        ),
        migrations.CreateModel(
            name='AppointmentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.appointment')),
            ],
            options={
                'verbose_name': 'Appointment Translation',
                'db_table': 'home_appointment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
